name = "inventory-app-egm"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "твой_url"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "твой_ключ"
